---

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      language: generic
      python: 
       - "2.7"
    - os: osx
      language: generic
      python: 
       - "2.7"

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  # Install Ansible with Homebrew on OS X
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ansible; fi

install:
  # Install Ansible with pip
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then pip install ansible; fi

  # Check Ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  # Basic role syntax check 
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check 
  # Test role run
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"
  # Test idempotence
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  email: false
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/